### ISSUE TITLE
Handle invalid keys

### ISSUE THREAD

**Issue by AmulAbasana** [NiklasMerz/cordova-plugin-fingerprint-aio#43] opened 2017-08-21 10:44 UTC
## Description
* What did you do?
used fingerprint-aio plugin in my application with property "disableBackup: true" for touch id authentication

* What did happen?
whenever i restart the phone and open the application it gives "Failed to init Cipher and backup disabled" with  Exception "Failed to init Cipher: InvalidKeyException: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated" .
after i clears the cache then it works fine.

* What did you expect to happen?
it should work even after phone restart
* Type of issue (bug, feature request)
bug
## Environment
Android 7.1.1 (Moto E4 Plus)
* Plugin version
1.2.1
* ```cordova platform ls```
Installed platforms:
  android 6.1.2
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)

### Logs

08-21 15:32:52.305 10391 10391 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 10391
08-21 15:32:52.339 10391 10515 W CordovaPlugin: Attempted to send a second callback for ID: Fingerprint1256258676
08-21 15:32:52.339 10391 10515 W CordovaPlugin: Result was: "OK"
08-21 15:32:52.358   982  1307 I libPerfService: 6: set: 1
08-21 15:32:52.358   982  1307 I libPerfService: 6: set freq: 0
08-21 15:32:52.380   982  1307 I libPerfService: 7: set freq: 819000
08-21 15:32:52.380   982  1307 I libPerfService: 7: set: 3
08-21 15:32:52.384 10391 10515 E Fingerprint: Failed to init Cipher: InvalidKeyException: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated
08-21 15:32:52.385 10391 10515 W PluginManager: THREAD WARNING: exec() call to Fingerprint.authenticate blocked the main thread for 25ms. Plugin should use CordovaInterface.getThreadPool().
08-21 15:32:52.404 10391 10391 E Fingerprint: Failed to init Cipher: InvalidKeyException: android.security.keystore.KeyPermanentlyInvalidatedException: Key permanently invalidated
08-21 15:32:52.404 10391 10391 W CordovaPlugin: Attempted to send a second callback for ID: Fingerprint1256258677
08-21 15:32:52.404 10391 10391 W CordovaPlugin: Result was: "Error"
08-21 15:32:52.409 10391 10391 I chromium: [INFO:CONSOLE(18)] "Failed to init Cipher and backup disabled.", source: file:///android_asset/www/build/main.js (18)

**Comment by NiklasMerz** [comment] 2017-08-27 09:24
Hi Amul. I finally got the emulator working to test this. I have encountered the same issue, but after reinstalling the app, it was fixed. Maybe the keystore got corrupted between test builds. I suggest you to try deleting the app and start with a clean build. Hopefully this will fix the problem for you, too. Please let me know if this fixes your problem.

**Comment by NiklasMerz** [comment] 2017-10-02 19:47
I am closing this now, since this not really reproducable.

To @AmulAbasana and anyone who has encountered similar errors: Please update this issue.

**Comment by NiklasMerz** [comment] 2017-10-12 19:13
On Android the key becomes invalid if Screenlock type was changed or finger are added.

see #58

**Comment by NiklasMerz** [comment] 2017-10-12 19:17
This error will be resolved with #54

**Closed by NiklasMerz** 2017-10-12 19:17 UTC
Labels: bug
